version: "3.7"

services:
  server:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ohgodiconfessimamess
      POSTGRES_USER: benjamin.mizrany
      POSTGRES_DB: gilgamesh-n8n
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    init: true
